### ISSUE TITLE
Dimension discrepancy for Deepbench

### ISSUE THREAD

**Issue by dagamayank** [openai/openai-gemm#4]
@scott-gray  I noticed that the dimensions (M, N, K) which are called out by Deepbench (https://github.com/baidu-research/DeepBench/blob/master/results/DeepBench_NV_TitanX_Pascal.xlsx) are different from those benchmarked by OpenAI-GEMM. For example what Deepbench calls (M, N, K, Op): 1760, 16, 1760, N, N is 16, 1760, 1760, 1760, N, N for OpenAI-GEMM. Therefore, M and N are flipped for this particular problem. Can you please explain this? As you will attest, the values of M, N and K can vastly affect performance, therefore, understanding this dimension discrepancy is important to get an idea of the performance.

**Comment by scott-gray** [comment]
My kernels are row-order, cublas is col-order.  So you need to swap M and N (and their transposes) for equivalence.

(A x B).T = B.T x A.T

**Comment by dagamayank** [comment]
Got it, makes sense now. Thanks !
