### ISSUE TITLE
Coalescing of A/B reads for non-vectorized loads

### ISSUE THREAD

**Issue by ptillet** [openai/openai-gemm#5]
Hi,

I've noticed the following lines:
```
--:-:2:-:1  \@P2 LDG.E.CI.$dtypeA loadA0, [trackA + ${dsizeA}x<0>];
--:-:2:-:1  \@P3 LDG.E.CI.$dtypeA loadA1, [trackA + ${dsizeA}x<1>];
--:-:2:-:1  \@P4 LDG.E.CI.$dtypeA loadA2, [trackA + ${dsizeA}x<2>];
--:-:2:-:1  \@P5 LDG.E.CI.$dtypeA loadA3, [trackA + ${dsizeA}x<3>];
```
So it seems like when the contiguous dimension of A or B is not a multiple of 4, the LDG will not be coalesced? On the other hand, I'm aware that this setting allows for the use of STS.128 -- which wouldn't be the case should each thread read contiguous elements. There seems to be some trade-off.

I've ran some experiments on my PTX GEMM kernels, where I have the same issue (it's a little bit easier to maintain this way :)). Here is what I found for float32:
- When the non-coherent cache is enabled (.CI), you'd rather have non-coalesced loads and use STS.128. The benefits were on the order of 2%.
- Otherwise, coalescing loads provides major benefits. The benefits were on the order of 15%.

One explanation is that the cacheline would be 16-bytes wide, in which case [trackA + {4, 8, 12}] would reside in the L2 cache once [trackA] has been loaded. If this is the case, then the current assembly code would remain optimal for float32, but might benefit from coalesced read for other data-types.

Another possibility is that my observations on poorly scheduled PTX code are not applicable to well-scheduled SASS where the latency of the STS would be hidden better. If STS.128 effectively provides no benefit, then loads should probably always be coalesced.

Any thoughts?

**Comment by scott-gray** [comment]
So I studied this like 2 years ago, but maybe it could still use more rigorous analysis.   The thinking goes that the texture cache is pretty good at strided memory access patterns provided you quickly request the holes in the strides.  This means that memory gets a nice deep fetch for the first access (deeper than a coalesced fetch), then the subsequent accesses are just served out of L1 (provided your stride is less than the 32 byte transaction size).

The other advantage is that the code is much easier to maintain for vector and non-vector pathways.

Also, in deep learning you can usually trivially add a few more features to enable vector loads and most of the time you aren't even using the non-vector pathway.  It's mainly there for completeness.

Anyway, here's some data with and without vector loads enabled by tweaking this line:
https://github.com/openai/openai-gemm/blob/master/openai_gemm.py#L269

TITAN X (Pascal) @ 1404MHz fixed

|     M|     N|     K| Op|no-vec_32|   vec_32|no-vec_16|   vec_16|
|------|------|------|---|---------|---------|---------|---------|
|    16|  3584|  3584| NN|     2416|     2476|     4580|     5074|
|    32|  3584|  3584| NN|     4461|     4779|     7512|     7855|
|    64|  3584|  3584| NN|     4831|     6276|     8284|     8582|
|   128|  3584|  3584| NN|     7787|     8997|     8838|     8945|

It looks like for fp16 the performance difference is about what you'd expect.  But for fp32, performance drops a little more than I'd expect without vector loads.  I'm getting the 75% tex_cache_hit_rate you'd expect so I'm not sure what's up.  Trying a coalesced pattern here instead might be informative.  Of course if your dimensions are odd (unlike here), then you'd also be dealing with overfetch issues in fp32.

**Comment by ptillet** [comment]
The fact that you get 75% tex_cache_hit_rate pretty much answers my question. It's probably not worth it to add a divergent path for setting trackA and trackB and make the bounds-checking predicates more tricky for the sake of completeness.

That said, it seems that the vecC you enabled in the python code is absent from the .sass file:
https://github.com/openai/openai-gemm/blob/master/sass/xgemm_32x32x32.sass

It seems like the code always goes through the trouble of re-organizing the tile to achieve coalesced loads/stores on C, although using vector loads-store should offer better-performance (if as your benchmark suggests it's more efficient than caching/coalescing).

**Comment by scott-gray** [comment]
The reason for that coalesced store on C is that strided writes don't get the same benefit as strided reads.  So you waste a lot of L2 transactions in the non-vector case.  At least the L2 does stage the writes for more efficient storage to DDR.  Anyway, I didn't want to keep two code paths for the vector and coalesced cases.  You'd only notice the performance difference for shallow reductions, which in deep learning can typically be avoided (by combining the time and minibatch dims for the grad-weight op).

The custom hgemm tiles do use vector stores on C so you can experiment on performance benefit with those.

There a number of things I could do to get these kernels to top performance across the board and this is one.. but I only have so much time to spend on these things.  This lib was just a quick side project for me (that I was meaning to share a lot of code with on other things).

**Comment by ptillet** [comment]
Well, at least that leaves room for my "long front project" to reach the same performance as your "quick side project"! :)
Anyway, thanks for the great work and the additional info. I'll re-open the issue if I ever have the time to try out the proposed changes.
