### ISSUE TITLE
convolution kernel support

### ISSUE THREAD

**Issue by feiyulv** [openai/openai-gemm#6]
Does openai-gemm has a scheduler to support convolution kernel?

**Comment by scott-gray** [comment]
Yes, we'll be releasing some new conv kernels (and tensorflow support) in the near future.

**Comment by feiyulv** [comment]
@scott-gray wonderful, by the way, is there any plan to support int8 gemm and conv?

**Comment by scott-gray** [comment]
Most likely yes.  We just have some other priorities to take care of first.

**Comment by feiyulv** [comment]
@scott-gray got it
